"""empty message

Revision ID: 2f45939e31d6
Revises: 97c8f778c334
Create Date: 2022-10-27 20:21:50.093142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f45939e31d6'
down_revision = '97c8f778c334'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('test', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
