"""empty message

Revision ID: 4122d1115f7d
Revises: 343b76d8943e
Create Date: 2022-10-22 08:38:38.642602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4122d1115f7d'
down_revision = '343b76d8943e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nutritionist', sa.Column('times', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nutritionist', 'times')
    # ### end Alembic commands ###
