"""empty message

Revision ID: 47775e3af8ad
Revises: 2cb1cde24da5
Create Date: 2022-10-18 18:25:16.002922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47775e3af8ad'
down_revision = '2cb1cde24da5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nutritionist', sa.Column('days', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nutritionist', 'days')
    # ### end Alembic commands ###
