"""empty message

Revision ID: 4850cb6f0c0b
Revises: c7bbdabffb48
Create Date: 2022-10-18 12:30:04.140676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4850cb6f0c0b'
down_revision = 'c7bbdabffb48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('professional', sa.Boolean(), nullable=False))
    op.add_column('nutritionist', sa.Column('professional', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nutritionist', 'professional')
    op.drop_column('client', 'professional')
    # ### end Alembic commands ###
