"""empty message

Revision ID: 4ecf19c295b0
Revises: 4b8848e16ff5
Create Date: 2022-10-08 09:58:57.261351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ecf19c295b0'
down_revision = '4b8848e16ff5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_client', sa.Integer(), nullable=False),
    sa.Column('id_nutritionist', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=100), nullable=False),
    sa.Column('recomendation', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('client', sa.Column('first_name', sa.String(length=120), nullable=False))
    op.add_column('client', sa.Column('last_name', sa.String(length=120), nullable=False))
    op.drop_column('client', 'name')
    op.add_column('nutritionist', sa.Column('first_name', sa.String(length=120), nullable=False))
    op.add_column('nutritionist', sa.Column('last_name', sa.String(length=120), nullable=False))
    op.drop_column('nutritionist', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nutritionist', sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_column('nutritionist', 'last_name')
    op.drop_column('nutritionist', 'first_name')
    op.add_column('client', sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_column('client', 'last_name')
    op.drop_column('client', 'first_name')
    op.drop_table('session')
    # ### end Alembic commands ###
