"""empty message

Revision ID: 86d20c7bda3b
Revises: 4850cb6f0c0b
Create Date: 2022-10-18 13:09:04.556222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86d20c7bda3b'
down_revision = '4850cb6f0c0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client', 'professional',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=80),
               existing_nullable=False)
    op.drop_column('nutritionist', 'professional')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nutritionist', sa.Column('professional', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.alter_column('client', 'professional',
               existing_type=sa.String(length=80),
               type_=sa.BOOLEAN(),
               existing_nullable=False)
    # ### end Alembic commands ###
