"""empty message

Revision ID: 9d78b3722776
Revises: bb42f8df3fda
Create Date: 2022-10-24 13:59:38.791185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d78b3722776'
down_revision = 'bb42f8df3fda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('session', 'id_client',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('session', 'id_nutritionist',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'session', 'client', ['id_client'], ['id'])
    op.create_foreign_key(None, 'session', 'nutritionist', ['id_nutritionist'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'session', type_='foreignkey')
    op.drop_constraint(None, 'session', type_='foreignkey')
    op.alter_column('session', 'id_nutritionist',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('session', 'id_client',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
