"""empty message

Revision ID: 9dde9f9fc31d
Revises: fd79a3d233de
Create Date: 2022-10-08 11:03:16.661811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dde9f9fc31d'
down_revision = 'fd79a3d233de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nutritionist', sa.Column('nutritionist_email', sa.String(length=120), nullable=False))
    op.drop_constraint('nutritionist_email_key', 'nutritionist', type_='unique')
    op.create_unique_constraint(None, 'nutritionist', ['nutritionist_email'])
    op.drop_column('nutritionist', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nutritionist', sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'nutritionist', type_='unique')
    op.create_unique_constraint('nutritionist_email_key', 'nutritionist', ['email'])
    op.drop_column('nutritionist', 'nutritionist_email')
    # ### end Alembic commands ###
