"""empty message

Revision ID: bb42f8df3fda
Revises: 4122d1115f7d
Create Date: 2022-10-22 08:42:34.339194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb42f8df3fda'
down_revision = '4122d1115f7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('times', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'times')
    # ### end Alembic commands ###
