"""empty message

Revision ID: c7bbdabffb48
Revises: 9dde9f9fc31d
Create Date: 2022-10-11 03:03:22.341647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7bbdabffb48'
down_revision = '9dde9f9fc31d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('client_email', sa.String(length=120), nullable=False))
    op.drop_constraint('client_email_key', 'client', type_='unique')
    op.create_unique_constraint(None, 'client', ['client_email'])
    op.drop_column('client', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'client', type_='unique')
    op.create_unique_constraint('client_email_key', 'client', ['email'])
    op.drop_column('client', 'client_email')
    # ### end Alembic commands ###
