"""empty message

Revision ID: e52f9853e5c8
Revises: 9d78b3722776
Create Date: 2022-10-25 16:58:53.550744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e52f9853e5c8'
down_revision = '9d78b3722776'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('time', sa.String(length=100), nullable=False))
    op.drop_column('session', 'recomendation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('recomendation', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.drop_column('session', 'time')
    # ### end Alembic commands ###
