"""empty message

Revision ID: e6139e07ef81
Revises: 4ecf19c295b0
Create Date: 2022-10-08 10:38:22.561607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6139e07ef81'
down_revision = '4ecf19c295b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('id_cLLient', sa.Integer(), nullable=False))
    op.drop_column('session', 'id_client')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('id_client', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('session', 'id_cLLient')
    # ### end Alembic commands ###
