"""empty message

Revision ID: fd79a3d233de
Revises: e6139e07ef81
Create Date: 2022-10-08 10:47:07.316326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd79a3d233de'
down_revision = 'e6139e07ef81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('id_client', sa.Integer(), nullable=False))
    op.drop_column('session', 'id_cLLient')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('id_cLLient', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('session', 'id_client')
    # ### end Alembic commands ###
